name: 'Read package version package.json'
description: 'Output the version specified in [path]/package.json'
author: 'xile611'
inputs:
  path:
    required: false
    description: 'The directory path of target json file'
    default: './'
  filename:
    required: false
    description: 'The file name you want to read, default value is package.json'
    default: 'package.json'
  field:
    required: false
    description: 'The field which specify the version you want to read'
    default: 'version'
  use_current_version:
    required: false
    description: 'parse current version when semver_string not defined'
    default: true
  semver_string:
    required: false
    description: 'The semver string that want to be parsed'
  semver_pattern:
    required: false
    description: 'The pattern to parse the semver string'
outputs:
  current_version:
    description: 'the current version'
  pre_release_type:
    description: 'the pre-release type parsed from semver_string or current version'
  pre_release_name:
    description: 'the pre-release name parsed from semver_string or current version'
  full:
    description: 'the full version parsed from semver_string or current version'
  major:
    description: 'the major version parsed from semver_string or current version'
  minor:
    description: 'the minor version parsed from semver_string or current version'
  patch:
    description: 'the patch version parsed from semver_string or current version'
  prerelease:
    description: 'the prerelease string parsed from semver_string or current version'
  build:
    description: 'the build string parsed from semver_string or current version '
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'award'
  color: 'green'
